version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /usr/src/app
    env_file:
      - .env