# Generated by Django 5.0.3 on 2024-03-15 14:34

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artist',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_name'),
        ),
    ]
