name: CI/CD

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set .env file"
        run: cp .env.example .env

      - name: Run tests
        run: docker-compose run --rm app pytest